accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.AccountDisplayView.as_view(), name='account_profile'),
    path('profile/<str:userid>/', views.AccountDisplayView.as_view(), name='account_view'),
    path('edit/<str:userid>/', views.AccountSettingsView.as_view(), name='account_edit'),
    path('analytics/<str:userid>/', views.AccountAnalyticsView.as_view(), name='account_analytics'),
    path('register/', views.CourseJoinView.as_view(), name='course_register'),
    path('register/<int:course_id>', views.CourseJoinView.as_view(), name='course_register_autocourse'),

    path('updateAccountAjax', views.AccountUpdateAjax.as_view()),
    path('courseJoinAjax', views.CourseJoinAjax.as_view()),
    path('registeredCourseAnalyticsAjax', views.RegisteredCourseAnalyticsAjax.as_view()),
    path('ownedCourseAnalyticsAjax', views.OwnedCourseAnalyticsAjax.as_view()),
    path('courseAssignmentAnalyticsAjax', views.CourseAssignmentAnalyticsAjax.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from home.views import *
from django.conf import settings
from django.conf.urls.static import static

handler400 = Error400View.as_view()
handler403 = Error403View.as_view()
handler404 = Error404View.as_view()
handler500 = error_500_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('announcements/', include('announcements.urls')),
    path('calendar/', include('event_calendar.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search/', SearchView.as_view(), name='search'),
    path('course/', include('courses.urls')),
    path('', include('home.urls')),
    path('students/', include('students.urls')),
    path('account/', include('accounts.urls')),
    path('', include('pwa.urls')),
    path('courseListAjax', CourseListAjax.as_view()),
    path('moduleListAjax', ModuleListAjax.as_view()),
    path('staffCourseListAjax', StaffCourseListAjax.as_view()),
    path('staffModuleListAjax', StaffModuleListAjax.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('queryAjax', views.QueryAjax.as_view()),
    #path('home/', views.home),

]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.hashers import make_password
import random

from .models import Profile, AccountSubmission


class UserCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].required = False

    def clean_userid(self):
        userid = str(self.cleaned_data['userid'])
        if userid is None or userid == '':
            for _ in range(100):
                userid = 'u' + ''.join([random.choice('0123456789') for __ in range(8)])
                if Profile.objects.filter(userid=userid).count() == 0:
                    return userid
            raise FailedGenerationError('Failed to generate unique userid')
        return userid

    def clean_password(self):
        password = self.cleaned_data['password']
        if password is None or password == '':
            return None
        return make_password(password)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('password') is None:
            cleaned_data['password'] = make_password(cleaned_data.get('userid'))

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Profile
        fields = ('userid', 'first_name', 'last_name', 'email', 'password')

    def clean_password(self):
        return self.initial["password"]

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'phone_number', 'term_address')

    def clean_password(self):
        return make_password(self.cleaned_data['password'])

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user


class CourseRegisterForm(forms.ModelForm):
    class Meta:
        model = AccountSubmission
        fields = ('email', 'course')

    def save(self, commit=True):
        submission = super().save(commit=False)
        if commit:
            submission.save()
        return submission


class FailedGenerationError(Exception):
    def __init(self, message="Failed attempt at generating default value"):
        self.message = message
        super().__init__(self.message)

accounts/views.py
import datetime
from statistics import mean
from typing import Dict, Sequence, Union

from django import forms
from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View

from courses.models import Course, Module, Subject, Assignment, Grade
from .forms import UserUpdateForm, CourseRegisterForm

User = get_user_model()


class AccountDisplayView(View):
    """
    View for displaying details of account specified in url
    Will show different results based on users permission level
    """
    template_name = 'accounts/account_view/account_view.html'

    def get(self, request: HttpRequest, userid: str = None) -> HttpResponse:
        current_user = request.user
        if userid is None:  # No userid specified in url
            if current_user.is_authenticated:
                # Redirect to current user's account page
                return redirect('/account/profile/' + current_user.userid)
            else:
                # Redirect to login page to authenticate
                return redirect('/accounts/login')
        else:
            account = get_object_or_404(User, userid=userid)
            if not (current_user.is_authenticated or account.is_staff):
                # Unauthenticated users can only view staff accounts, otherwise redirect home
                return redirect('/')
        user_details = get_user_details(account, current_user)
        context = {
            "user_details": user_details,
            "is_user": current_user == account,
            "show_analytics": current_user == account or current_user.has_perm('accounts.view_profile'),
        }
        return render(request, self.template_name, context)


class AccountSettingsView(View):
    """
    View for displaying editable user details and other preferences
    """
    template_name = 'accounts/account_view/account_settings.html'

    def get(self, request: HttpRequest, userid: str) -> HttpResponse:
        current_user = request.user
        account = get_object_or_404(User, userid=userid)
        if not current_user.is_authenticated:
            return redirect('login')
        elif current_user == account:
            user_details = get_user_details(account, current_user)
            context = {
                "user_details": user_details,
                "is_user": True,
                "show_analytics": True,
            }
            return render(request, self.template_name, context)
        else:
            return redirect('/')


class AccountAnalyticsView(View):
    """
    View for displaying general account analytics of a given user
    """
    template_name = 'accounts/account_view/account_analytics.html'

    def get(self, request: HttpRequest, userid: str) -> HttpResponse:
        current_user = request.user
        account = get_object_or_404(User, userid=userid)
        if not current_user.is_authenticated:
            return redirect('login')
        elif current_user == account or current_user.has_perm('accounts.view_account'):
            user_details = get_user_details(account, current_user)
            context = {
                "user_details": user_details,
                "is_user": current_user == account,
                "show_analytics": True,

                "registered_courses": Course.objects.filter(students__in=[account]).order_by('title'),
                "owned_courses": Course.objects.filter(owner=account).order_by('title'),
            }
            return render(request, self.template_name, context)
        else:
            return redirect('/')


class CourseJoinView(View):
    """
    View for students to submit a request to join a course / create a new account
    """
    template_name = 'accounts/account_create/course_join.html'

    def get(self, request: HttpRequest, course_id: int = None) -> HttpResponse:
        current_user = request.user
        courses = Course.objects.filter(id=course_id)
        context = {
            "subjects": Subject.objects.all(),
            "courses": Course.objects.all(),
            "autocourse": None if not courses.exists() else courses[0]
        }
        return render(request, self.template_name, context)


class AccountUpdateAjax(View):
    """
    Ajax submission for updating existing accounts
    """

    def post(self, request: HttpRequest) -> JsonResponse:
        current_user = request.user
        account = get_object_or_404(User, userid=request.POST['userid'])
        if current_user.is_authenticated and current_user == account:
            form = UserUpdateForm(request.POST, instance=account)
            if form.is_valid():
                user = form.save()
                user.clean()
                return JsonResponse({})
            else:
                return invalid_form_response(form)
        else:
            response = JsonResponse({})
            response.status_code = 401
            return response


class CourseJoinAjax(View):
    """
    Ajax submission for course registration
    """

    def post(self, request: HttpRequest) -> JsonResponse:
        current_user = request.user
        if (current_user.is_authenticated and request.POST['email'] == current_user.email
                and not current_user.has_perm('accounts.can_add_account_submission')):
            response = JsonResponse({
                "responseMessage": "Permission Denied. You do not have authorisation to make changes to this account"
            })
            response.status_code = 401
            return response
        else:
            form = CourseRegisterForm({
                'email': request.POST['email'],
                'course': Course.objects.get(id=request.POST['course']),
            })
            if form.is_valid():
                submission = form.save()
                submission.clean()
                return JsonResponse({})
            else:
                return invalid_form_response(form)


class RegisteredCourseAnalyticsAjax(View):
    """Ajax request for analytics data relating to courses the given user is registered to"""

    def post(self, request: HttpRequest) -> JsonResponse:
        current_user = request.user
        account = User.objects.get(userid=request.POST['account'])
        response = validate_account_view_ajax(current_user, account)
        if response:
            return response
        course = Course.objects.get(id=request.POST.get('course'))

        context = {"graphs": []}
        if account.is_student:
            # Graph all grades for provided account and course
            assignments = Assignment.objects.filter(module__course=course).order_by('order')
            assignment_marks_data = []
            assignment_marks_label = []
            assignment_marks_meta = []
            invalid_indexes = []
            for assignment in assignments:
                grades = Grade.objects.filter(student=account, assignment=assignment)
                if grades.exists():
                    grade = grades.latest('datetime_submitted')
                    assignment_marks_data.append(grade.grade)
                    assignment_marks_label.append(assignment.title)
                    assignment_marks_meta.append("submitted: " + str(grade.datetime_submitted))
                else:
                    assignment_marks_data.append(0)
                    assignment_marks_label.append(assignment.title)
                    assignment_marks_meta.append("Not submitted")
                    invalid_indexes.append(len(assignment_marks_data) - 1)

            context["graphs"].append({
                "container_id": "registered-course-1",
                "title": "assignment marks",
                "type": "bar",
                "data": assignment_marks_data,
                "label": assignment_marks_label,
                "color": STANDARD_GRADIENT,
                "meta": assignment_marks_meta,
                "invalid": invalid_indexes,
                "yUnit": "%",
                "xLabel": "date submitted",
                "yLabel": "marks (%)",
            })

            # Graph number of assignments completed against total number of assignments for course
            total = assignments.count()
            completed = Grade.objects.filter(
                assignment__in=assignments,
                student=account,
            ).distinct('assignment', 'student').count()
            context["graphs"].append({
                "container_id": "registered-course-2",
                "title": "course progress",
                "type": "pie",
                "data": [completed, total - completed],
                "label": ["completed", "uncompleted"],
                "color": {
                    "type": "list",
                    "value": ["#00AA22", "#22222288"]
                },
            })

            context['module_progress'] = []
            for module in Module.objects.filter(course=course):
                # Graph number of assignments completed for module in course
                module_assignments = assignments.filter(module=module)
                total = module_assignments.count()
                completed = Grade.objects.filter(
                    assignment__in=module_assignments,
                    student=account,
                ).distinct('assignment', 'student').count()
                context["graphs"].append({
                    "container_id": "registered-course-3",
                    "title": "module: " + module.title,
                    "type": "pie",
                    "data": [completed, total - completed],
                    "label": ["completed", "uncompleted"],
                    "color": {
                        "type": "list",
                        "value": ["#00AA22", "#22222288"]
                    },
                })

        return JsonResponse(context)


class OwnedCourseAnalyticsAjax(View):

accounts/templates/accounts/account_view/account_analytics.html
{% extends "accounts/account_view/account_view_base.html" %}
{% load static %}

{% block navigation %}
    <a href="{% url 'accounts:account_view' user_details.userid %}">Profile</a>/
    <a href="{% url 'accounts:account_analytics' user_details.userid %}">Analytics</a>/
{% endblock %}

{% block account_view_content %}
    {% if request.user.is_student %}
        <div id="registered-course-graphs" style="width: 100%">
            {% if registered_courses %}
                <h2>Courses you are registered in</h2>
                <div id="registered-course-navbar" class="navbar">
                    <h3>Select Course:</h3>
                    <div>
                        {% for course in registered_courses %}
                            <p data-value="{{ course.id }}"
                               data-function="updateRegisteredGraphs">{{ course.title }}</p>
                        {% endfor %}
                    </div>
                </div>
                <pre id="registered-response-pre" class="response-text"></pre>

                <div class="container-numbers"></div>
                <div class="container-graphs"></div>
            {% else %}
                <h3>You are currently not registered for any courses</h3>
            {% endif %}
        </div>
    {% endif %}
    {% if request.user.is_staff %}
        <div id="owned-course-graphs" style="width: 100%">
            {% if owned_courses %}
                <h2>Courses you own</h2>
                <div id="owned-course-navbar" class="navbar">
                    <h3>Select Course:</h3>
                    <div>
                        {% for course in owned_courses %}
                            <p data-value="{{ course.id }}"
                               data-function="updateOwnedGraphs">{{ course.title }}</p>
                        {% endfor %}
                    </div>
                </div>
                <pre id="owned-response-pre" class="response-text"></pre>

                <div class="container-numbers"></div>
                <div class="container-graphs"></div>
            {% else %}
                <h3>You currently own no courses</h3>
            {% endif %}
        </div>
        <div id="course-assignment-graphs" style="width: 100%">
            {% if owned_courses %}
                <h3 id="assignment-header">Course [] Modules</h3>
                <div id="course-assignment-navbars" style="width: 100%"></div>
                <pre id="assignment-response-pre" class="response-text"></pre>

                <div class="container-numbers"></div>
                <div class="container-graphs"></div>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}
{% block extrajavascript %}
    <script src={% static 'js/graphs.js' %}></script>
    <script>
        /**
         * Fill container with graphs of the given data.
         * @param {jQuery} container - jQuery element to contain the graphs.
         * @param {Array.<Object>} graphData - Array of Objects defining data and format of graphs to be rendered.
         *                                     {@link graphOptions graph options}.
         * @param {String} graphData[].container_id - Id of the graph container to put the graph in.
         *                                            Set multiple graphs to the same id to position them
         *                                            in line with each other.
         */
        function addGraphs(container, graphData) {
            for (let graph of graphData) {
                // Put graphs with the same container id in the same div
                let graphContainer = $('#' + graph.container_id);
                if (!graphContainer.length) {
                    graphContainer = $('<div>').attr('id', graph.container_id)
                        .addClass('graph-container').addClass(graph.type);
                    container.append(graphContainer);
                }
                setToGraph(
                    graphContainer[0],
                    graph
                );
            }
        }

        /**
         * Fill container with numerical statistics from the given data
         * @param {jQuery} container - jQuery element to contain the stats.
         * @param {Array.<Object>} numberData - Array of objects, each defining the parameters of a statistic.
         * @param {String} numberData[].container_id - Id of the stat container to put the stats in.
         *                                                 Set multiple stats to the same id to position them
         *                                                 in line with each other.
         * @param {String} numberData[].name - Name of the statistic or very short description.
         * @param {*} numberData[].value - Value of the statistic.
         * @param [units] - Units to be appended to value.
         */
        function addStats(container, numberData, units = '') {
            for (let stat of numberData) {
                let numbersContainer = $('#' + stat.container_id);
                if (!numbersContainer.length) {
                    numbersContainer = $('<div>').attr('id', stat.container_id)
                        .addClass('numbers-container')
                    container.append(numbersContainer);
                }
                let value = stat.value;
                if (value % 1 === 0) {
                    value = Math.round(value);
                } else {
                    value = value.toPrecision(3)
                }
                numbersContainer.append(
                    $('<p>').text(stat.name + ":" + value)
                )
            }
        }

        /**
         * Empty all child elements containing graphs
         * @param parent - Parent element to empty
         */
        function clearGraphs(parent) {
            parent.find('.container-graphs').each(function (index, element) {
                $(element).html('');
            });
            parent.find('.container-numbers').each(function (index, element) {
                $(element).html('');
            });
        }

        /**
         * Query then set registered course graph data for the given course
         * @param course - Course id to query data for
         */
        function updateRegisteredGraphs(course) {
            standardAjaxCall(
                '/account/registeredCourseAnalyticsAjax',
                {
                    "account": "{{ user_details.userid }}",
                    "course": course
                },
                function (response) {
                    // Clear any existing response text
                    standardSuccessResponse('', $('#registered-response-pre'));
                    let registeredCourses = $('#registered-course-graphs');
                    clearGraphs(registeredCourses);
                    let graphsContainer = registeredCourses.find('.container-graphs');
                    let numbersContainer = registeredCourses.find('.container-numbers');

                    if (response.number_data !== undefined)
                        addStats(numbersContainer, response.number_data);
                    if (response.graphs !== undefined)
                        addGraphs(graphsContainer, response.graphs);
                },
                function (response) {
                    standardErrorResponse(response, $('#registered-response-pre'));
                }
            );
        }

        /**
         * Query then set owned course graph data for the given course
         * @param course - Course id to query data for
         */
        function updateOwnedGraphs(course) {
            standardAjaxCall(
                '/account/ownedCourseAnalyticsAjax',
                {
                    "account": "{{ user_details.userid }}",
                    "course": course
                },
                function (response) {
                    // Clear any existing response text
                    standardSuccessResponse('', $('#owned-response-pre'));
                    $('#assignment-header').text('Course [' + response.title + '] Modules');

                    let ownedCourses = $('#owned-course-graphs');
                    clearGraphs(ownedCourses);
                    let graphsContainer = ownedCourses.find('.container-graphs');
                    let numbersContainer = ownedCourses.find('.container-numbers');

                    if (response.number_data !== undefined)
                        addStats(numbersContainer, response.number_data);
                    if (response.graphs !== undefined)
                        addGraphs(graphsContainer, response.graphs);

                    if (response.modules !== undefined) {
                        let navbarContainer = $('#course-assignment-navbars');
                        navbarContainer.html('');
                        let navbars = []
                        for (let module in response.modules) {
                            navbarContainer.append($('<h4>').text(response.modules[module].name));
                            let navbar = $('<div>').addClass('navbar').addClass('navbar-no-auto');
                            navbar.append($('<h3>').text('Select Assignment:'));
                            let linkContainer = $('<div>');
                            navbar.append(linkContainer);
                            navbarContainer.append(navbar);
                            for (let assignment of response.modules[module].assignments) {
                                linkContainer.append(
                                    $('<p>')
                                    .attr('data-value', assignment.id)
                                    .attr('data-function', 'updateCourseAssignmentGraphs')
                                    .text(assignment.label)
                                );
                            }
                            navbars.push(navbar);
                        }
                        for (let n of navbars) {
                            updateNavbar(n, navbars);
                        }
                    }
                },
                function (response) {
                    standardErrorResponse(response, $('#owned-response-pre'));
                }
            );
        }

        /**
         * Query then set course assignment graph data for the given assignment
         * @param assignment - Assignment id to query data for
         */
        function updateCourseAssignmentGraphs(assignment) {
            standardAjaxCall(
                '/account/courseAssignmentAnalyticsAjax',
                {
                    "account": "{{ user_details.userid }}",
                    "assignment": assignment
                },
                function (response) {
                    standardSuccessResponse('', $('assignment-response-pre'));

                    let courseAssignments = $('#course-assignment-graphs');
                    clearGraphs(courseAssignments);
                    let graphsContainer = courseAssignments.find('.container-graphs');
                    let numbersContainer = courseAssignments.find('.container-numbers');

                    if (response.number_data !== undefined)
                        addStats(numbersContainer, response.number_data);
                    if (response.graphs !== undefined)
                        addGraphs(graphsContainer, response.graphs);
                },
                function (response) {
                    standardErrorResponse(response, $('#assignment-response-pre'));
                }
            );
        }
    </script>
{% endblock %}

accounts/templates/accounts/account_view/account_settings.html
{% extends "accounts/account_view/account_view_base.html" %}

{% block navigation %}
    <a href="{% url 'accounts:account_view' user_details.userid %}">Profile</a>/
    <a href="{% url 'accounts:account_edit' user_details.userid %}">Settings</a>/
{% endblock %}

{% block account_view_content %}
    <form id="account-update-form" method="post" action="">
        <h3>UID:[{{ user_details.userid }}]</h3>
        <input type="hidden" name="userid" value="{{ user_details.userid }}">
        <p><label for="first-name">First Name(s):</label>
            <input id="first-name" type="text" name="first_name"
                   class="validate_text_not_empty"
                   value="{{ user_details.firstname }}">
        <p>
        <p><label for="last-name">Last Name:</label>
            <input id="last-name" type="text" name="last_name"
                   value="{{ user_details.lastname }}"></p>

        <h3>Contacts:</h3>
        {% for contact in user_details.contacts %}

            <p><label for="contact-{{ contact.name }}">{{ contact.show_as }}:</label>
                <input id="contact-{{ contact.name }}" type="text" name="{{ contact.name }}"
                       class="validate_text_{{ contact.name }}"
                       value="{{ contact.value }}"></p>

        {% endfor %}

        <input class="button effect" style="color:black;" type="submit" value="Save">
        <pre class="response-text"></pre>
    </form>
{% endblock %}
{% block extrajavascript %}
    <script>
        $(document).ready(function () {
            let accountForm = $('#account-update-form');
            assignStandardFormSetup(
                accountForm,
                '/account/updateAccountAjax',
                function (response) {
                    standardSuccessResponse(
                        'Updated account at ' + (new Date().toLocaleTimeString()),
                        accountForm
                    );
                },
                function (response) {
                    standardErrorResponse(response, accountForm);
                }
            );
        });
    </script>
{% endblock %}

accounts/templates/accounts/account_view/account_view_base.html
{% extends "base.html" %}

{% block title %}
    Account {{ user_details.userid }}
{% endblock %}

{% block content %}
    <div style="float: right; height: 100%">
        <div id="account-side-menu" class="side-menu border-l side-link-container"
             data-compress-function="sideMenuPartialCompress">
            <h3 class="hide-when-small">Profile:</h3>
            <button class="compress-button"><i class="fas fa-bars"></i></button>
        </div>
    </div>

    <div style="width: auto; height: 100%; overflow: hidden">
        {% block account_view_content %}
        {% endblock %}
    </div>

    <script>
    postSetup.push(profileSetup)
    function profileSetup() {
        loadNavigator(
            $('#account-side-menu'),
            [
                {
                    href: '{% url 'accounts:account_view' user_details.userid %}',
                    text: 'Profile',
                    type: 'link',
                    icon: 'fas fa-user-circle',
                },
                {% if is_user %}
                {
                    href: '{% url 'accounts:account_edit' user_details.userid %}',
                    text: 'Settings',
                    type: 'link',
                    icon: 'fas fa-sliders-h',
                },
                {% endif %}
                {% if show_analytics %}
                {
                    href: '{% url 'accounts:account_analytics' user_details.userid %}',
                    text: 'Analytics',
                    type: 'link',
                    icon: 'fas fa-chart-line',
                }
                {% endif %}
            ],
            false
        )
    }
    </script>
{% endblock %}