config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from home.views import *
from django.conf import settings
from django.conf.urls.static import static

handler400 = Error400View.as_view()
handler403 = Error403View.as_view()
handler404 = Error404View.as_view()
handler500 = error_500_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('announcements/', include('announcements.urls')),
    path('calendar/', include('event_calendar.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search/', SearchView.as_view(), name='search'),
    path('course/', include('courses.urls')),
    path('', include('home.urls')),
    path('students/', include('students.urls')),
    path('account/', include('accounts.urls')),
    path('', include('pwa.urls')),
    path('courseListAjax', CourseListAjax.as_view()),
    path('moduleListAjax', ModuleListAjax.as_view()),
    path('staffCourseListAjax', StaffCourseListAjax.as_view()),
    path('staffModuleListAjax', StaffModuleListAjax.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

event_calendar/urls.py
from . import views
from django.urls import path

app_name = 'event_calendar'
#These are the urls for the pages that call view functions which will render the display to the respective pages.
urlpatterns = [
    path('view/', views.CalendarView.as_view(), name='calendar'),
    path(r'^event/(?P<event_id>\d+)/$', views.event, name='event'),
    path('event_new/', views.event, name='event_new'),
]

home/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('queryAjax', views.QueryAjax.as_view()),
    #path('home/', views.home),

]

event_calendar/models.py
from django.db import models
from django.urls import reverse

from courses.models import Course

#This class creates Event model within database with the following attributes.
#As PostgreSQL is being used, primary key does not need to be defined.
class Event(models.Model):
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    #Foreign key from courses model.
    course = models.ForeignKey('courses.Course', on_delete=models.SET_NULL, null=True)

    #Property that adds hyperlink to each event displayed on calendar so they can be
    #clicked to view details about them that are displayed using forms.py
    @property
    def get_html_url(self):
        url = reverse('event_calendar:event', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

event_calendar/forms.py
from django.forms import ModelForm, DateInput
from event_calendar.models import Event

#The EventForm class created a form using the Django library ModelForm. The library is used to
# a form using the data fields of the event model. This class is specifically used to create a
#form that will be populated with data about an event which has been clicked on.
class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields.
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'

    #This function adds widgets to each field to set them to read only, so the user cannot
    #edit them when viewing the populated data.
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['readonly'] = True
        self.fields['description'].widget.attrs['readonly'] = True
        #Select fields cannot be set to readonly so disabled widget has to be used.
        self.fields['course'].widget.attrs['disabled'] = True
        self.fields['description'].widget.attrs['textarea'] = True
        self.fields['start_time'].widget.attrs['readonly'] = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].widget.attrs['readonly'] = ('%Y-%m-%dT%H:%M',)


#This class is used by staff to either edit existing events or to add new events.
class EventNewForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields.
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventNewForm, self).__init__(*args, **kwargs)
        # input_formats parses HTML5 datetime-local input to datetime field.
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

event_calendar/views.py
import calendar
from datetime import datetime, timedelta, date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.safestring import mark_safe
from django.views import generic
from .forms import EventForm, EventNewForm
from .models import *
from .utils import Calendar


class CalendarView(LoginRequiredMixin, generic.ListView):
    # This class is used to display the calendar with the next and previous month buttons,
    # and the current date so the calendar knows what page to start on.

    model = Event
    # The template to render view to.
    template_name = 'calendar.html'

    # Function to get all data that is needed such as the current datetime, the calendar and next/previous buttons
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


# This function gets the current datetime
def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


# This function calculates the previous month that will be displayed when the button is pressed.
def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


# This function calculates the next month that will be displayed when the button is pressed.
def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


# This function gets the id of an event when it is clicked and populates a form with the data
# about that form that the user can then see.
def event(request, event_id=None):
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
        # if a user is a staff member display the form that is not read only so they can edit calendar entries
        # and change the template so that they can save their changes
    if request.user.is_staff:
        form = EventNewForm(request.POST or None, instance=instance)
        template = "edit_event.html"
    # else display events as read only
    else:
        form = EventForm(request.POST or None, instance=instance)
        template = "event.html"
    form.fields['course'].queryset = Course.objects.filter(Q(owner=request.user) | Q(students__in=[request.user]))
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('event_calendar:calendar'))
    return render(request, template, {'form': form, 'event_id': event_id})

event_calendar/templates/calendar.html
{% extends "base.html" %}
{% block title %}Calendar{% endblock %}
{% block navigation %}
    <a href="{% url 'event_calendar:calendar' %}">Calendar</a>/
{% endblock %}

{% block h1 %}

    <h1>Calendar</h1>
{% endblock %}
{% block content %}



    <div class="container">
        <div class="row">
            <div class="col-6 col-sm-10">
                <a class="button effect"
                   href="{% url 'event_calendar:calendar' %}?{{ prev_month }}"><span
                        class="fas fa-arrow-circle-left"></span> Previous Month </a>
            </div>
            <div class="col-6 col-sm-2">
                <a style="align:right !important;" class="button effect"
                   href="{% url 'event_calendar:calendar' %}?{{ next_month }}">Next Month <span
                        class="fas fa-arrow-circle-right"></span></a>
            </div>

            <div class="table-responsive">

                {{ calendar }}
            </div>
        </div>
    </div>
{% endblock %}

event_calendar/templates/edit_event.html
{% extends 'base.html' %}
{% block title %}Edit Event{% endblock %}
{% block h1 %}
    <h1>Event</h1>
{% endblock %}


{% block content %}


    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ field.label }} <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <div class="col-12">
        <div class="module">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <br/><br/><button class="link-button" type="submit"><span class="fas fa-check-circle"></span> Save Changes </button>
            </form>
        </div>
    </div>

{% endblock %}

event_calendar/templates/event.html
{% extends 'base.html' %}
{% block title %}Event{% endblock %}
{% block h1 %}
    <h1>Event</h1>
{% endblock %}


{% block content %}


    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ field.label }} <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <div class="col-12">
        <div class="module">
            <form method="post">
                {% csrf_token %}
                {{ form }}
            </form>
        </div>
    </div>

{% endblock %}

event_calendar/templates/event_new.html
{% extends 'base.html' %}
{% block title %}
    Add Event
{% endblock %}
{% block navigation %}
    <a href="{% url 'event_calendar:calendar' %}">Calendar</a>/
    <a href="{% url 'event_calendar:event_new' %}">{% if event_id %}Edit {{ event_id }}{% else %}Add{% endif %}</a>/
{% endblock %}

{% block content %}
    {% if event_id %}
        <h1>Edit Event {{ event_id }}</h1>
    {% else %}
        <h1>New Event</h1>
    {% endif %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ field.label }} <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit" class="button effect"><span class="fas fa-calendar-plus"></span> Add New
            Event
        </button>
    </form>
{% endblock %}