config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from home.views import *
from django.conf import settings
from django.conf.urls.static import static

handler400 = Error400View.as_view()
handler403 = Error403View.as_view()
handler404 = Error404View.as_view()
handler500 = error_500_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('announcements/', include('announcements.urls')),
    path('calendar/', include('event_calendar.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search/', SearchView.as_view(), name='search'),
    path('course/', include('courses.urls')),
    path('', include('home.urls')),
    path('students/', include('students.urls')),
    path('account/', include('accounts.urls')),
    path('', include('pwa.urls')),
    path('courseListAjax', CourseListAjax.as_view()),
    path('moduleListAjax', ModuleListAjax.as_view()),
    path('staffCourseListAjax', StaffCourseListAjax.as_view()),
    path('staffModuleListAjax', StaffModuleListAjax.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('queryAjax', views.QueryAjax.as_view()),
    #path('home/', views.home),

]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('register/',
         views.StudentRegistrationView.as_view(),
         name='student_registration'),
    path('enroll-course/',
         views.StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('courses/',
         views.StudentCourseListView.as_view(),
         name='student_course_list'),
    path('courses/<pk>',
         views.StudentHomePageView.as_view(),
         name='student_home_page'),
    path('course/<pk>/',
         views.StudentCourseListView.as_view(),
         name='student_course_detail'),
    path('course/<pk>/module/<module_id>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
    path('course/<pk>/module/<module_id>/homepage/',
         views.ModuleHomePageView.as_view(),
         name='module_home_page'),
    path('assignments/<pk>/assignments/',
         views.AssignmentListStudentView.as_view(),
         name='assignments_list_student_view'),
    path('course/<pk>/module/<module_id>/assignments/',
         views.AssignmentListStudentView.as_view(),
         name='assignments_list_student_view_module'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/',
         views.AssignmentDetailStudentView.as_view(),
         name='student_assignment_detail'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/submission/',
         views.AssignmentSubmissionView.as_view(), {"redo": False},
         name='assignment_submission'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/submitted/redo/',
         views.AssignmentSubmissionView.as_view(), {"redo": True},
         name='assignment_submission_redo'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/submitted/',
         views.AssignmentSubmittedView.as_view(),
         name='assignment_submitted_view'),
    path('course/<pk>/quizzes/',
         views.QuizListStudentView.as_view(),
         name='quiz_list_student_view'),
    path('course/<pk>/module/<module_id>/quizzes/',
         views.QuizListStudentView.as_view(),
         name='quiz_list_student_view_module'),
    path('course/<pk>/module/<module_id>/quiz/<quiz_id>/',
         views.QuizSubmissionView.as_view(), {"redo": False},
         name='quiz_detail_student_view'),
    path('course/<pk>/module/<module_id>/quiz/<quiz_id>/redo/',
         views.QuizSubmissionView.as_view(), {"redo": True},
         name='quiz_detail_student_view_redo'),
    path('course/<pk>/module/<module_id>/quiz/<quiz_id>/submitted/',
         views.QuizSubmittedView.as_view(),
         name='quiz_submitted_view'),
    path('course/<pk>/module/<module_id>/content/',
         views.ModuleContentView.as_view(),
         name='module_content_view'),
]

courses/models.py
from django.db.models.signals import m2m_changed
from django.utils import timezone
from django.contrib.auth.models import User, Group
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from accounts.models import Profile
from .fields import OrderField
from django.template.loader import render_to_string
from django.conf import settings


class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Course(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name='courses_created',
                              on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject,
                                related_name='courses',
                                on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      related_name='courses_joined',
                                      blank=True)
    staff = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   related_name='courses_assisted',
                                   blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title


class Module(models.Model):
    course = models.ForeignKey(Course,
                               related_name='modules',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.order}.{self.title}'


class Assignment(models.Model):
    module = models.ForeignKey('courses.Module',
                               related_name='assignments',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['module'])
    due_date = models.DateTimeField(null=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.title


class Content(models.Model):
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     limit_choices_to={'model__in': (
                                         'text',
                                         'file',
                                         'image',
                                         'video'
                                     )})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')

    class Meta:
        ordering = ['order']
        abstract = True


class ModuleContent(Content):
    module = models.ForeignKey(Module,
                               related_name='contents',
                               on_delete=models.CASCADE)
    order = OrderField(blank=True, for_fields=['module'])


class AssignmentContent(Content):
    assignment = models.ForeignKey(Assignment,
                                   related_name='contents',
                                   on_delete=models.CASCADE)
    order = OrderField(blank=True, for_fields=['assignment'])


class ItemBase(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name='%(class)s_related',
                              on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string(
            f'courses/content/{self._meta.model_name}.html',
            {'item': self}
        )


class Text(ItemBase):
    content = models.TextField()


class File(ItemBase):
    file = models.FileField(upload_to='files')


class Image(ItemBase):
    file = models.FileField(upload_to='images')


class Video(ItemBase):
    url = models.URLField()


class Quiz(models.Model):
    title = models.CharField(max_length=50)
    module = models.ForeignKey(Module,
                               on_delete=models.CASCADE,
                               related_name='quizzes')
    description = models.TextField()
    date_created = models.DateTimeField('date created', null=True)
    due_date = models.DateTimeField(null=True)

    class Meta:
        verbose_name_plural = 'quizzes'

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz,
                             on_delete=models.CASCADE,
                             related_name='questions')
    number = models.PositiveIntegerField()
    question_text = models.TextField()

    def __str__(self):
        return str(self.number)


class Choice(models.Model):
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE,
                                 related_name='choices',
                                 null=True)
    choice_text = models.CharField(max_length=100)
    correct_answer = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'choice'
        verbose_name_plural = 'choices'

    def __str__(self):
        return self.choice_text


class Grade(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name='grades')
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                null=True)
    assignment = models.ForeignKey(Assignment,
                                   on_delete=models.SET_NULL,
                                   null=True,
                                   blank=True)
    grade = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    datetime_started = models.DateTimeField()
    datetime_submitted = models.DateTimeField(default=None)

    @property
    def time_taken(self):
        return self.datetime_submitted - self.datetime_started

    def __str__(self):
        return f'{self.assignment}:{self.student}:{self.grade}'

students/models.py
from django.db import models
from config import settings
from courses.models import Assignment, Course, Quiz, Question


class AssignmentSubmission(models.Model):
    assignment = models.ForeignKey(Assignment,
                                   on_delete=models.PROTECT,
                                   related_name='submissions')

    student = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                null=True)
    course = models.ForeignKey(Course,
                               on_delete=models.PROTECT)
    date_submitted = models.DateTimeField(auto_now_add=True)
    submitted_file = models.FileField(upload_to='submitted_assignments')


class QuizSubmission(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.PROTECT,
                                default=None)
    date_submitted = models.DateTimeField(auto_now=True)
    quiz = models.ForeignKey(Quiz,
                             on_delete=models.CASCADE,
                             related_name='submissions',
                             default=None)
    score = models.PositiveIntegerField(null=True,
                                        default=0)

    def __str__(self):
        return self.date_submitted


class QuizAnswer(models.Model):
    quiz_submission = models.ForeignKey(QuizSubmission,
                                        on_delete=models.CASCADE,
                                        related_name='answers',
                                        default=None)
    answer = models.CharField(max_length=50)
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE,
                                 default=None)
    is_correct = models.BooleanField(default=None)

    def __str__(self):
        return self.answer

students/forms.py
from django import forms
from django.forms import inlineformset_factory, ModelForm, ModelMultipleChoiceField

from courses.models import Course, Question, Choice
from students.models import QuizAnswer


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all(),
                                    widget=forms.HiddenInput)


class QuizAnswerForm(forms.Form):
    answer = forms.CharField()

students/templates/students/assignments/detail.html
{% extends "students/course/detail.html" %}

{% block extrabreadcrumbs %}
    <a href="{% url 'students:assignments_list_student_view_module' course.id module.id %}">Assignments</a>/
    <a href="{% url 'students:student_assignment_detail' course.id module.id assignment.id %}">
        Assignment:{{ assignment.id }}</a>/
{% endblock %}

{% block subcontent %}
    <h2>{{ assignment.title }}</h2>
    <div style="overflow: hidden">
        <p style="float: left; margin: 0">Assignment Due: {{ assignment.due_date }}</p>
        <a href="{% url 'students:assignment_submission' course.id module.id assignment.id %}"
           class="link-button" style="float: right; height: 100%">
            Assignment Submission
        </a>
    </div>

    <div class="plain-text-area" style="height: 100%">
        {% for content in assignment.contents.all %}
            <h3>{{ content.item.title }}</h3>
            {{ content.item.render }}
        {% endfor %}
    </div>
{% endblock %}

students/templates/students/assignments/list.html
{% extends "students/course/detail.html" %}

{% block extrabreadcrumbs %}
    <a href="{% url 'students:assignments_list_student_view_module' course.id module.id %}">Assignments</a>
{% endblock %}

{% block subcontent %}
     <div>
        {% for assignment in assignment_list %}
            <div class="link-list">
                <a class="a-header"
                   href="{% url 'students:student_assignment_detail' course.id module.id assignment.id %}">
                    {{ assignment.title }}
                </a>
                <div class="plain-text-area">{{ assignment.description }}</div>
            </div>
        {% empty %}
            <p>This module has no assignments yet</p>
        {% endfor %}
    </div>
{% endblock %}

students/templates/students/assignments/submission.html
{% extends "students/course/detail.html" %}

{% block extrabreadcrumbs %}
    <a href="{% url 'students:assignments_list_student_view_module' course.id module.id %}">Assignments</a>/
    <a href="{% url 'students:student_assignment_detail' course.id module.id assignment.id %}">
        Assignment:{{ assignment.id }}</a>/
    <a href="{% url 'students:assignment_submission' course.id module.id assignment.id %}">Submission</a>/
{% endblock %}

{% block subcontent %}
    <h2>{{ assignment.title }}</h2>
    <p style="float: left; margin: 0">Assignment Due: {{ assignment.due_date }}</p>
    <a href="{% url 'students:student_assignment_detail' course.id module.id assignment.id %}"
       class="link-button" style="float: right">Back to Assignment</a>
    <div class="plain-text-area" style="overflow: hidden">
        <form action="" method="post" enctype="multipart/form-data" class="file-submit-form">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" value="Submit">Submit Assignment</button>
        </form>
    </div>
{% endblock %}

students/templates/students/assignments/submitted.html
{% extends "students/course/detail.html" %}

{% block extrabreadcrumbs %}
    <a href="{% url 'students:assignments_list_student_view_module' course.id module.id %}">Assignments</a>/
    <a href="{% url 'students:student_assignment_detail' course.id module.id assignment.id %}">
        Assignment:{{ assignment.id }}</a>/
    <a href="{% url 'students:assignment_submission' course.id module.id assignment.id %}">Submission</a>/
{% endblock %}

{% block subcontent %}
    <h2>{{ submission.assignment.title }}</h2>
    <div style="border-bottom: 2px solid var(--main-vdark-col); overflow: hidden">
        <div style="float: left">
            <p>Date submitted: {{ submission.date_submitted }}</p>
            {% if grade %}
                <p>Score: {{ grade.grade }}/100</p>
            {% else %}
                <p>Score: [Not Marked]</p>
            {% endif %}
        </div>
        <div style="float: right;">
            <a href="{% url 'students:assignments_list_student_view_module' course.id module.id %}"
               class="link-button" style="width: 100%; display: inline-block">Back to Assignments</a>
            {% if not overdue %}
                <br>
                <a href="{% url 'students:assignment_submission_redo' course.id module.id assignment.id %}"
                   class="link-button" style="width: 100%; display: inline-block">Re-submit</a>
            {% endif %}
        </div>
    </div>
{% endblock %}