config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from home.views import *
from django.conf import settings
from django.conf.urls.static import static

handler400 = Error400View.as_view()
handler403 = Error403View.as_view()
handler404 = Error404View.as_view()
handler500 = error_500_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('announcements/', include('announcements.urls')),
    path('calendar/', include('event_calendar.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('search/', SearchView.as_view(), name='search'),
    path('course/', include('courses.urls')),
    path('', include('home.urls')),
    path('students/', include('students.urls')),
    path('account/', include('accounts.urls')),
    path('', include('pwa.urls')),
    path('courseListAjax', CourseListAjax.as_view()),
    path('moduleListAjax', ModuleListAjax.as_view()),
    path('staffCourseListAjax', StaffCourseListAjax.as_view()),
    path('staffModuleListAjax', StaffModuleListAjax.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path('mine/',
         views.ManageCourseListView.as_view(),
         name='manage_course_list'),
    path('create/',
         views.CourseCreateView.as_view(),
         name='course_create'),
    path('<pk>/edit/',
         views.CourseUpdateView.as_view(),
         name='course_edit'),
    path('<pk>/delete/',
         views.CourseDeleteView.as_view(),
         name='course_delete'),
    path('<pk>/module/',
         views.CourseModuleUpdateView.as_view(),
         name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_update'),
    path('content/<int:id>/delete/',
         views.ContentDeleteView.as_view(),
         name='module_content_delete'),
    path('question/<int:id>/delete/',
         views.QuestionDeleteView.as_view(),
         name='question_delete'),
    path('module/<int:module_id>/',
         views.ModuleListView.as_view(),
         name='module_list'),
    path('module/<int:module_id>/content/',
         views.ModuleContentListView.as_view(),
         name='module_content_list'),
    path('module/<int:module_id>/assignments/',
         views.AssignmentContentListView.as_view(),
         name='assignment_content_list'),
    path('module/<int:module_id>/assignments/create/',
         views.CourseAssignmentUpdateView.as_view(),
         name='course_assignment_update'),
    path('module/<int:module_id>/assignments/<int:assignment_id>/',
         views.AssignmentUpdateView.as_view(),
         name='assignment_update'),
    path('module/<int:module_id>/assignments/<int:assignment_id>/content/<model_name>/create/',
         views.AssignmentCreateUpdateView.as_view(),
         name='assignment_content_create'),
    path('module/<int:module_id>/quizzes/',
         views.QuizListView.as_view(),
         name='quiz_list_view'),
    path('module/<int:module_id>/quizzes/create/',
         views.QuizCreateView.as_view(),
         name='quiz_create'),
    path('module/<int:module_id>/quizzes/<int:quiz_id>/',
         views.QuizUpdateView.as_view(),
         name='quiz_edit'),
    path('module/<int:module_id>/quizzes/<int:quiz_id>/add_question/',
         views.QuizCreateUpdateView.as_view(),
         name='quiz_questions_create'),
    path('module/<int:module_id>/quizzes/<int:quiz_id>/<int:question_id>/add_choice/',
         views.AddChoiceView.as_view(),
         name='edit_choices'),
    path('module/order/', views.ModuleOrderView.as_view(),
         name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(),
         name='content_order'),
    path('subject/<slug:subject>/',
         views.CourseListView.as_view(),
         name='course_list_subject'),
    path('all/',
         views.CourseListView.as_view(),
         name='course_list'),
    path('<slug:slug>/',
         views.CourseDetailView.as_view(),
         name='course_detail'),
]

home/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('queryAjax', views.QueryAjax.as_view()),
    #path('home/', views.home),

]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('register/',
         views.StudentRegistrationView.as_view(),
         name='student_registration'),
    path('enroll-course/',
         views.StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('courses/',
         views.StudentCourseListView.as_view(),
         name='student_course_list'),
    path('courses/<pk>',
         views.StudentHomePageView.as_view(),
         name='student_home_page'),
    path('course/<pk>/',
         views.StudentCourseListView.as_view(),
         name='student_course_detail'),
    path('course/<pk>/module/<module_id>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
    path('course/<pk>/module/<module_id>/homepage/',
         views.ModuleHomePageView.as_view(),
         name='module_home_page'),
    path('assignments/<pk>/assignments/',
         views.AssignmentListStudentView.as_view(),
         name='assignments_list_student_view'),
    path('course/<pk>/module/<module_id>/assignments/',
         views.AssignmentListStudentView.as_view(),
         name='assignments_list_student_view_module'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/',
         views.AssignmentDetailStudentView.as_view(),
         name='student_assignment_detail'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/submission/',
         views.AssignmentSubmissionView.as_view(), {"redo": False},
         name='assignment_submission'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/submitted/redo/',
         views.AssignmentSubmissionView.as_view(), {"redo": True},
         name='assignment_submission_redo'),
    path('course/<pk>/module/<module_id>/assignment/<assignment_id>/submitted/',
         views.AssignmentSubmittedView.as_view(),
         name='assignment_submitted_view'),
    path('course/<pk>/quizzes/',
         views.QuizListStudentView.as_view(),
         name='quiz_list_student_view'),
    path('course/<pk>/module/<module_id>/quizzes/',
         views.QuizListStudentView.as_view(),
         name='quiz_list_student_view_module'),
    path('course/<pk>/module/<module_id>/quiz/<quiz_id>/',
         views.QuizSubmissionView.as_view(), {"redo": False},
         name='quiz_detail_student_view'),
    path('course/<pk>/module/<module_id>/quiz/<quiz_id>/redo/',
         views.QuizSubmissionView.as_view(), {"redo": True},
         name='quiz_detail_student_view_redo'),
    path('course/<pk>/module/<module_id>/quiz/<quiz_id>/submitted/',
         views.QuizSubmittedView.as_view(),
         name='quiz_submitted_view'),
    path('course/<pk>/module/<module_id>/content/',
         views.ModuleContentView.as_view(),
         name='module_content_view'),
]

students/views.py
import datetime

from django.apps import apps
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelform_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView

from courses.models import Course, Module, Assignment, Grade
from courses.models import Quiz, Question, Choice
from .forms import CourseEnrollForm
from .models import QuizAnswer, QuizSubmission, AssignmentSubmission


class StudentRegistrationView(CreateView):
    """Renders a registration form for new users to create
    an account"""
    template_name = 'students/student/registration.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('students:student_course_list')

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'],
                            password=cd['password1'])
        login(self.request, user)
        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    """Checks user is logged in and renders a form to enroll
    on a course"""
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('students:student_course_detail',
                            args=[self.course.id])


class ModulePageMixin:
    """Mixin to provide other views necessary objects"""
    def get_context(self, request, course_id=None, module_id=None, assignment_id=None, quiz_id=None, **kwargs):
        context = {}
        context["course_list"] = Course.objects.filter(students__in=[request.user]).order_by('id')
        context["course"] = None if course_id is None else get_object_or_404(Course, id=course_id)
        context["module_list"] = (None if context["course"] is None
                                  else Module.objects.filter(course=context["course"]).order_by('order'))
        context["module"] = None if module_id is None else get_object_or_404(Module, id=module_id)
        context["assignment_list"] = (None if context["module"] is None
                                      else Assignment.objects.filter(module=context["module"]))
        context["assignment"] = None if assignment_id is None else get_object_or_404(Assignment, id=assignment_id)
        context["quiz_list"] = (None if context["module"] is None
                                else Quiz.objects.filter(module=context["module"]))
        context["quiz"] = None if quiz_id is None else get_object_or_404(Quiz, id=quiz_id)
        return context


class StudentCourseListView(LoginRequiredMixin, ModulePageMixin, View):
    """Renders list of courses students are enrolled in"""
    template_name = 'students/course/list.html'

    def get(self, request, pk=None):
        context = self.get_context(request, pk)
        return render(request, self.template_name, context)


class StudentCourseDetailView(LoginRequiredMixin, View):
    """Redirects to module home page"""
    def get(self, request, pk, module_id):
        return redirect('students:module_home_page', pk=pk, module_id=module_id)


class ModuleHomePageView(LoginRequiredMixin, ModulePageMixin, View):
    """Renders module home page"""
    template_name = 'students/course/module_home.html'

    def get(self, request, pk, module_id):
        context = self.get_context(request, pk, module_id)
        return render(request, self.template_name, context)


class StudentHomePageView(LoginRequiredMixin, ModulePageMixin, View):
    """Renders student home page with list of courses enrolled on"""
    template_name = 'students/home.html'

    def get(self, request, pk, module_id):

        context = self.get_context(request, pk, module_id)
        return render(request, self.template_name, context)


class AssignmentListStudentView(LoginRequiredMixin, ModulePageMixin, View):
    """Renders a list of assignments relative to the module selected"""
    template_name = 'students/assignments/list.html'

    def get(self, request, pk, module_id):
        context = self.get_context(request, pk, module_id)
        return render(request, self.template_name, context)


class QuizListStudentView(LoginRequiredMixin, ModulePageMixin, View):
    """Renders a list of quizzes relative to the module selected"""
    template_name = 'students/quizzes/list.html'

    def get(self, request, pk, module_id):
        context = self.get_context(request, pk, module_id)
        return render(request, self.template_name, context)


class AssignmentDetailStudentView(LoginRequiredMixin, ModulePageMixin, View):
    """Renders assignment contents based on assignment selected"""
    template_name = 'students/assignments/detail.html'

    def get(self, request, pk, module_id, assignment_id):
        context = self.get_context(request, pk, module_id, assignment_id=assignment_id)
        return render(request, self.template_name, context)


class AssignmentSubmissionView(TemplateResponseMixin, ModulePageMixin, View):
    """Renders a form for students to submit a file"""
    model = None
    module = None
    course = None
    assignment = None
    obj = None
    template_name = 'students/assignments/submission.html'

    def get_model(self):
        return apps.get_model(app_label='students',
                              model_name='AssignmentSubmission')

    def get_form(self, model, *args, **kwargs):
        Form = modelform_factory(model, exclude=['assignment',
                                                 'course',
                                                 'date_of_submission',
                                                 'student'
                                                 ])
        return Form(*args, **kwargs)

    def dispatch(self, request, pk, module_id, assignment_id, id=None, redo=None):
        self.assignment = get_object_or_404(Assignment,
                                            id=assignment_id)
        self.module = get_object_or_404(Module,
                                        id=module_id)
        self.course = get_object_or_404(Course,
                                        id=pk)
        self.model = self.get_model()
        if id:
            self.obj = get_object_or_404(self.model,
                                         id=id,
                                         owner=request.user)
        return super().dispatch(request, pk, module_id, assignment_id, id, redo=redo)

    def get(self, request, pk, module_id, assignment_id, id=None, redo=None):
        form = self.get_form(self.model, instance=self.obj)
        context = self.get_context(request, pk, module_id, assignment_id=assignment_id)
        context["form"] = form
        context["object"] = self.obj
        if not redo and AssignmentSubmission.objects.filter(assignment=context["assignment"],
                                                            student=request.user).count():
            return redirect("students:assignment_submitted_view", pk, module_id, assignment_id)
        elif context["assignment"].due_date is not None and context["assignment"].due_date < datetime.datetime.now():
            context["overdue"] = True
            return redirect("students:assignment_submitted_view", pk, module_id, assignment_id)
        return self.render_to_response(context)

    def post(self, request, course_id, module_id, assignment_id, id=None, redo=None):
        form = self.get_form(self.model,
                             files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.student = request.user
            obj.assignment = self.assignment
            obj.course = self.course
            obj.submitted_file = request.FILES['submitted_file']
            obj.save()
            return redirect('students:assignment_submitted_view', self.course.id, self.module.id, self.assignment.id)
        return self.render_to_response({'form': form,
                                        'object': self.obj})


class QuizSubmissionView(TemplateResponseMixin, ModulePageMixin, View):
    """Renders a quizzes questions and multiple choice answers
    as radio buttons"""
    model = None
    module = None
    course = None
    quiz = None
    obj = None
    template_name = 'students/quizzes/detail.html'

    def get_model(self):
        return apps.get_model(app_label='students',
                              model_name='QuizAnswer')

    def dispatch(self, request, pk, module_id, quiz_id, id=None, redo=None):
        self.quiz = get_object_or_404(Quiz,
                                      id=quiz_id)
        self.module = get_object_or_404(Module,
                                        id=module_id)
        self.course = get_object_or_404(Course,
                                        id=pk)
        self.model = self.get_model()
        if id:
            self.obj = get_object_or_404(self.model,
                                         id=id,
                                         owner=request.user)
        return super().dispatch(request, pk, module_id, quiz_id, id, redo=redo)

    def get(self, request, pk, module_id, quiz_id, id=None, redo=None):
        context = self.get_context(request, pk, module_id, quiz_id=quiz_id)
        context["object"] = self.obj
        if not redo and QuizSubmission.objects.filter(quiz=context["quiz"],
                                                      student=request.user).count():
            return redirect("students:quiz_submitted_view", pk, module_id, quiz_id)

students/templates/students/course/detail.html
{% extends "base.html" %}

{% block title %}
    {{ object.title }}
{% endblock %}
{% block navigation %}
    <a href="{% url 'students:student_course_list' %}">Courses</a>/
    <a href="{% url 'students:student_course_detail' course.id %}">Course:{{ course.id }}</a>/
    {% if module %}
        {% url 'students:student_course_detail_module' course.id module.id as module_url%}
        <a href="{{ module_url }}">Module:{{ module.id }}</a>/
    {% endif %}
    {% block extrabreadcrumbs %}{% endblock %}
{% endblock %}
{% block header %}
    <h1>Course: {{ course.title }}<br>Module: {{ module.title }}</h1>
{% endblock %}

{% block content %}
    <div style="height: 100%; overflow: visible">
        {% include 'students/course/module_sidebar.html' %}
        <div style="width: auto; height: 100%; overflow: hidden">
            <div class="navbar navbar-function-link">
                <h3>  Navigate:</h3>
                <div>
                    <p data-link="{% url 'students:module_home_page' course.id module.id %}">Module Home</p>
                    <p data-link="{% url 'students:module_content_view' course.id module.id %}">Content</p>
                    <p data-link="{% url 'students:assignments_list_student_view_module' course.id module.id %}">Assignments</p>
                    <p data-link="{% url 'students:quiz_list_student_view_module' course.id module.id %}">Quizzes</p>
                </div>
            </div>
            <div id="module-content" style="width: 100%; height: 100%">
                {% block subcontent %}{% endblock %}
            </div>
        </div>
    </div>


{% endblock %}

students/templates/students/course/list.html
{% extends "base.html" %}

{% block title %}My Courses{% endblock %}
{% block navigation %}
    <a href="{% url 'students:student_course_list' %}">Courses</a>/
    {% if course %}
        <a href="{% url 'students:student_course_detail' course.id %}">Course:{{ course.id }}</a>/
    {% endif %}
{% endblock %}
{% block header %}
    <h1>Enrolled Courses</h1>
{% endblock %}

{% block content %}
    {% if course_list %}
        <div class="navbar navbar-function-link">
            <h3> Select Course:</h3>
            <div>
            {% for course in course_list %}
                <p data-link="{% url 'students:student_course_detail' course.id %}">
                    {{ course.title }}
                </p>
            {% endfor %}
            </div>
        </div>
        <div style="height: 100%">
            {% if course %}
                {% include 'students/course/module_sidebar.html' %}
                <div style="width: auto; height: 100%; overflow: hidden">
                    <h3 class="hide-when-small">Overview:</h3>
                    <div class="plain-text-area" style="height: 100%">
                        {{ course.overview }}
                    </div>
                </div>
            {% endif %}
        </div>
    {% else %}
        <p>
            You are not enrolled in any courses yet.
            <a href="{% url 'courses:course_list' %}">Browse courses</a>
        </p>
    {% endif %}

{% endblock %}

students/templates/students/course/module_home.html
{% extends "students/course/detail.html" %}

{% block extrabreadcrumbs %}
    <a href="{% url 'students:module_home_page' course.id module.id %}">Homepage</a>
{% endblock %}

{% block subcontent %}
    <div class="plain-text-area" style="height: 100%">
        {{ module.description }}
    </div>
{% endblock %}

students/templates/students/course/module_sidebar.html
<div style="float: right; height: 100%">
    <div id="module-side-menu" class="side-menu border-l side-link-container"
         data-compress-function="sideMenuFullCompress">
        <h3 class="hide-when-small">Modules:</h3>
        <button class="compress-button"><i class="fas fa-bars"></i></button>
    </div>
</div>

<script>
    postSetup.push(setup);

    function setup() {
        loadNavigator(
            $('#module-side-menu'),
            [
                {% for m in module_list %}
                    {
                        href: '{% url 'students:student_course_detail_module' course.id m.id %}',
                        text: '{{ m.title }}',
                        icon: 'fas fa-book-open',
                        type: 'link',
                    },
                {% endfor %}
            ],
            false
        );
    }
</script>